// <auto-generated />
namespace Bootcamp.CRUD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingTransactionsItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingTransactionsItems));
        
        string IMigrationMetadata.Id
        {
            get { return "201901240442450_addingTransactionsItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
