// <auto-generated />
namespace Bootcamp.CRUD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingtrigger2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingtrigger2));
        
        string IMigrationMetadata.Id
        {
            get { return "201901241230354_addingtrigger2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
